### ISSUE TITLE
`unknown[]` type of arguments for `history` methods

### ISSUE THREAD

**Issue by faminchik** [salvoravida/redux-first-history#50]
`push`, `replace`, `go`, `goBack`, `goForward` history methods have `unknown[]` type for arguments.

![image](https://user-images.githubusercontent.com/31989569/141486062-50ab1d1b-0367-4ed3-88cf-e3efaddc0077.png)

**Comment by salvoravida** [comment]
@faminchik please upgrade to 5.x it should be fixed

**Comment by salvoravida** [comment]
@faminchik lmk if it solves your issue

**Comment by faminchik** [comment]
@salvoravida

Hello Salvatore,

I've installed `redux-first-history` `v 5.0.1` and `history` v `5.1.0`, but this issue still exists
____

If take a look at the `actions.d.ts` file, I see the following:

``` ts
export declare const push: (...args: Parameters<History[HistoryMethods]>) => ReduxAction;
export declare const replace: (...args: Parameters<History[HistoryMethods]>) => ReduxAction;
export declare const go: (...args: Parameters<History[HistoryMethods]>) => ReduxAction;
export declare const goBack: (...args: Parameters<History[HistoryMethods]>) => ReduxAction;
export declare const goForward: (...args: Parameters<History[HistoryMethods]>) => ReduxAction;

export declare type HistoryMethods = 'push' | 'replace' | 'go' | 'goBack' | 'goForward';
```

And since all these five methods have nothing in common, then args have `unknown[]` type.

I guess the reason is in [the following function](https://github.com/salvoravida/redux-first-history/blob/aa3de08083fc8a94e2409513c33d29eb8f14e96b/src/actions.ts#L14).

**Comment by salvoravida** [comment]
> @salvoravida
> 
> Hello Salvatore,
> 
> I've installed `redux-first-history` `v5.0.1` and `history` `v5.1.0`, but this issue still exists
> 
> If take a look at the `actions.d.ts` file, I see the following:
> 
> ```ts
> export declare const push: (...args: Parameters<History[HistoryMethods]>) => ReduxAction;
> export declare const replace: (...args: Parameters<History[HistoryMethods]>) => ReduxAction;
> export declare const go: (...args: Parameters<History[HistoryMethods]>) => ReduxAction;
> export declare const goBack: (...args: Parameters<History[HistoryMethods]>) => ReduxAction;
> export declare const goForward: (...args: Parameters<History[HistoryMethods]>) => ReduxAction;
> 
> export declare type HistoryMethods = 'push' | 'replace' | 'go' | 'goBack' | 'goForward';
> ```
> 
> And since all these five methods have nothing in common, then `args` have `unknown[]` type.
> 
> I guess the reason is in [the following function](https://github.com/salvoravida/redux-first-history/blob/aa3de08083fc8a94e2409513c33d29eb8f14e96b/src/actions.ts#L14).

Please try 5.0.2. Can you create a codesandbox?
